import { Section } from './shared';

export function MemoSection({ memo }: { memo: any }) {
  return (
    <Section title="IC Memo (AI-generated)">
      <div className="mb-4">
        <div className="text-lg font-semibold text-zinc-100 leading-snug">{memo.headline}</div>
        <div className="mt-1 text-xs text-zinc-500 font-mono">
          Generated by {memo.generatedBy}
          {memo.promptTokens !== null && (
            <>
              {' '}
              · {memo.promptTokens} / {memo.completionTokens} tok
            </>
          )}
        </div>
      </div>

      <div className="mb-4 rounded border border-zinc-800 bg-zinc-950/40 p-3">
        <div className="text-xs uppercase tracking-wide text-zinc-500 mb-1">Executive Summary</div>
        <p className="text-sm text-zinc-200 leading-relaxed">{memo.executiveSummary}</p>
      </div>

      <div className="grid md:grid-cols-2 gap-3 mb-4">
        <div className="rounded border border-zinc-800 p-3">
          <div className="text-xs uppercase tracking-wide text-emerald-400 mb-1">Base Case</div>
          <p className="text-sm text-zinc-300 leading-relaxed">{memo.baseCaseNarrative}</p>
        </div>
        <div className="rounded border border-zinc-800 p-3">
          <div className="text-xs uppercase tracking-wide text-rose-400 mb-1">Downside</div>
          <p className="text-sm text-zinc-300 leading-relaxed">{memo.downsideNarrative}</p>
        </div>
      </div>

      {memo.negotiationPlaybook.length > 0 && (
        <div className="mb-4">
          <div className="text-xs uppercase tracking-wide text-indigo-400 mb-2">
            Negotiation Playbook
          </div>
          <ul className="space-y-1.5 text-sm text-zinc-200">
            {memo.negotiationPlaybook.map((p: string, i: number) => (
              <li key={i} className="flex gap-2">
                <span className="text-indigo-500 font-mono shrink-0">
                  {String(i + 1).padStart(2, '0')}.
                </span>
                <span className="leading-relaxed">{p}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <div className="rounded border border-indigo-900/60 bg-indigo-950/30 p-3">
        <div className="text-xs uppercase tracking-wide text-indigo-400 mb-1">
          Recommended Action
        </div>
        <p className="text-sm text-indigo-100 leading-relaxed font-medium">
          {memo.recommendedAction}
        </p>
      </div>
    </Section>
  );
}
